name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.19
          - 1.18
          - 1.17
          - 1.16
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build & Test
        run: |
          go test -race ./...
